import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart' show Colors; // Helper
import 'package:hive_flutter/hive_flutter.dart';
import 'package:just_audio_background/just_audio_background.dart';
import 'package:provider/provider.dart';
import 'package:ultimate_player/models/playlist.dart';
import 'package:ultimate_player/models/song.dart';
import 'package:ultimate_player/providers/audio_provider.dart';
import 'package:ultimate_player/providers/playlist_provider.dart';
import 'package:ultimate_player/screens/home_screen.dart';
import 'package:ultimate_player/widgets/mini_player.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive
  await Hive.initFlutter();
  
  // Register Adapters (Generated by build_runner)
  Hive.registerAdapter(SongAdapter());
  Hive.registerAdapter(PlaylistAdapter());
  
  // Initialize Background Audio
  await JustAudioBackground.init(
    androidNotificationChannelId: 'com.ryanheise.bg_demo.channel.audio',
    androidNotificationChannelName: 'Audio playback',
    androidNotificationOngoing: true,
  );

  runApp(const UltimatePlayerApp());
}

class UltimatePlayerApp extends StatelessWidget {
  const UltimatePlayerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => PlaylistProvider()),
        ChangeNotifierProvider(create: (_) => AudioProvider()),
      ],
      child: const CupertinoApp(
        title: 'UPlayer',
        theme: const CupertinoThemeData(
          primaryColor: CupertinoColors.systemGreen,
          // Removed explicit brightness to allow system default (Dark/Light)
        ),
        home: MainLayout(),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}

class MainLayout extends StatelessWidget {
  const MainLayout({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        const HomeScreen(),
        const Positioned(
          left: 0,
          right: 0,
          bottom: 0,
          child: MiniPlayer(),
        ),
      ],
    );
  }
}
